global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'local'
    scrape_interval: 5s
    static_configs:
      - targets: ['mac:9100']
  - job_name: 'sample'
    scrape_interval: 5s
    static_configs:
      - targets: ['sample1:8080', 'sample2:8080']
        labels:
          group: 'production'
      - targets: ['sample3:8080']
        labels:
          group: 'canary'
